package:
  name: ros-galactic-qt-gui-cpp
  version: 2.0.1
source:
  git_url: https://github.com/ros2-gbp/qt_gui_core-release.git
  git_rev: release/galactic/qt_gui_cpp/2.0.1-1
  folder: ros-galactic-qt-gui-cpp/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): pkg-config
  host:
    - python
    - qt-main
    - ros-galactic-ament-cmake
    - ros-galactic-ament-cmake-pytest
    - ros-galactic-pluginlib
    - ros-galactic-python-qt-binding
    - ros-galactic-rcpputils
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-tinyxml2-vendor
    - ros2-distro-mutex 0.1 galactic
    - sel(build_platform == target_platform): pkg-config
  run:
    - python
    - ros-galactic-pluginlib
    - ros-galactic-qt-gui
    - ros-galactic-rcpputils
    - ros-galactic-ros-workspace
    - ros-galactic-tinyxml2-vendor
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
