package:
  name: ros-galactic-rqt-image-view
  version: 1.1.1
source:
  git_url: https://github.com/ros2-gbp/rqt_image_view-release.git
  git_rev: release/galactic/rqt_image_view/1.1.1-2
  folder: ros-galactic-rqt-image-view/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - qt-main
    - ros-galactic-ament-cmake
    - ros-galactic-cv-bridge
    - ros-galactic-geometry-msgs
    - ros-galactic-image-transport
    - ros-galactic-qt-gui-cpp
    - ros-galactic-rclcpp
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-rqt-gui
    - ros-galactic-rqt-gui-cpp
    - ros-galactic-sensor-msgs
    - ros2-distro-mutex 0.1 galactic
  run:
    - python
    - ros-galactic-cv-bridge
    - ros-galactic-geometry-msgs
    - ros-galactic-image-transport
    - ros-galactic-qt-gui-cpp
    - ros-galactic-rclcpp
    - ros-galactic-ros-workspace
    - ros-galactic-rqt-gui
    - ros-galactic-rqt-gui-cpp
    - ros-galactic-sensor-msgs
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
