package:
  name: ros-galactic-teleop-twist-joy
  version: 2.4.3
source:
  git_url: https://github.com/ros2-gbp/teleop_twist_joy-release.git
  git_rev: release/galactic/teleop_twist_joy/2.4.3-1
  folder: ros-galactic-teleop-twist-joy/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-galactic-ament-cmake
    - ros-galactic-ament-lint-auto
    - ros-galactic-ament-lint-common
    - ros-galactic-geometry-msgs
    - ros-galactic-launch-ros
    - ros-galactic-launch-testing-ament-cmake
    - ros-galactic-launch-testing-ros
    - ros-galactic-rclcpp
    - ros-galactic-rclcpp-components
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-sensor-msgs
    - ros2-distro-mutex 0.1 galactic
  run:
    - python
    - ros-galactic-geometry-msgs
    - ros-galactic-joy
    - ros-galactic-rclcpp
    - ros-galactic-rclcpp-components
    - ros-galactic-ros-workspace
    - ros-galactic-sensor-msgs
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
