package:
  name: ros-galactic-resource-retriever
  version: 2.5.0
source:
  git_url: https://github.com/ros2-gbp/resource_retriever-release.git
  git_rev: release/galactic/resource_retriever/2.5.0-2
  folder: ros-galactic-resource-retriever/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - pytest
    - python
    - ros-galactic-ament-cmake-gtest
    - ros-galactic-ament-cmake-pytest
    - ros-galactic-ament-cmake-ros
    - ros-galactic-ament-index-cpp
    - ros-galactic-ament-index-python
    - ros-galactic-ament-lint-auto
    - ros-galactic-ament-lint-common
    - ros-galactic-libcurl-vendor
    - ros-galactic-python-cmake-module
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.1 galactic
  run:
    - python
    - ros-galactic-ament-index-cpp
    - ros-galactic-ament-index-python
    - ros-galactic-libcurl-vendor
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
