package:
  name: ros-galactic-python-qt-binding
  version: 1.0.8
source:
  git_url: https://github.com/ros2-gbp/python_qt_binding-release.git
  git_rev: release/galactic/python_qt_binding/1.0.8-1
  folder: ros-galactic-python-qt-binding/src/work
  patches:
    - patch/ros-galactic-python-qt-binding.patch

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - pyqt 5.12
    - python
    - qt-main
    - ros-galactic-ament-cmake
    - ros-galactic-ament-cmake-pytest
    - ros-galactic-ament-lint-auto
    - ros-galactic-ament-lint-common
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.1 galactic
  run:
    - pyqt
    - python
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
