package:
  name: ros-galactic-rqt-py-common
  version: 1.1.2
source:
  git_url: https://github.com/ros2-gbp/rqt-release.git
  git_rev: release/galactic/rqt_py_common/1.1.2-1
  folder: ros-galactic-rqt-py-common/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - python
    - qt-main
    - ros-galactic-ament-cmake
    - ros-galactic-ament-cmake-pytest
    - ros-galactic-python-cmake-module
    - ros-galactic-rclpy
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros-galactic-rosidl-default-generators
    - ros-galactic-rosidl-default-runtime
    - ros2-distro-mutex 0.1 galactic
  run:
    - python
    - qt-main
    - ros-galactic-python-qt-binding
    - ros-galactic-qt-gui
    - ros-galactic-rclpy
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
