package:
  name: ros-galactic-rqt-plot
  version: 1.1.0
source:
  git_url: https://github.com/ros2-gbp/rqt_plot-release.git
  git_rev: release/galactic/rqt_plot/1.1.0-1
  folder: ros-galactic-rqt-plot/src/work

build:
  script:
    sel(win): bld_ament_python.bat
    sel(unix): build_ament_python.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-galactic-ros-environment
    - ros-galactic-ros-workspace
    - ros2-distro-mutex 0.1 galactic
  run:
    - catkin_pkg
    - matplotlib-base
    - numpy
    - python
    - ros-galactic-python-qt-binding
    - ros-galactic-qt-gui-py-common
    - ros-galactic-rclpy
    - ros-galactic-ros-workspace
    - ros-galactic-rqt-gui
    - ros-galactic-rqt-gui-py
    - ros-galactic-rqt-py-common
    - ros-galactic-std-msgs
    - ros2-distro-mutex 0.1 galactic
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
